# Generated by Django 3.2.23 on 2023-11-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='hotels',
        ),
    ]
